import Header from "./components/Header";

export const metadata = {
  title: "Open Table",
  description: "Generated by create next app",
};

export default function RestaurantLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div>{children}</div>
    </>
  );
}
